### PR TITLE
Feature/make parsing pre existing crontab optional

### PR DESCRIPTION
**Pull request by dbsr**
We use this bundle in  bamboo and would like to be able to (optionally) disable parsing pre existing crontabs.

### CODE REVIEW

**Comment by blaugueux** [comment]
@dbsr Nice work here :+1: 

Could you please add a line inside the Readme so other users can be able to know that this functionality exist. Then squash your commits and I'll merge your PR right away.

**Comment by dbsr** [comment]
Done and done, thanks for the quick response :)

**Comment by blaugueux** [comment]
Thanks @dbsr

**Comment by RWOverdijk** [comment]
Nice

**Comment by atomtm** [comment]
Is there a way you can change the user?

**Pull request merged**
